### PR TITLE
Fix regression race condition

### PR DESCRIPTION
**Pull request by alxvth**
I'm currently running into a race-condition when zooming in an image in the image viewer. (I don't know where this comes from exactly, but going back on the master https://github.com/ManiVaultStudio/core/commit/b1e70ec64cc05da5a1cd32f49f3145c4091f625c seems to somehow trigger this).

When zooming in, `LayersRenderer::setZoomPercentage` keeps being called recursively which leads to an instant crash.

This PR solves that recursion by just updating zoom percentages and rectangles if they changed. We can't just check `_zoomPercentageAction.getValue() == zoomPercentage` since internally a zoom percentage is floating-point-stored as e.g. `0.0100001` for a zoom percentage of `0.01`. [qFuzzyCompare](https://doc.qt.io/qt-6/qtnumeric.html#qFuzzyCompare-1) does not allow for a precision, but I think comparing with an epsilon is pretty straight forward.

Even if I didn't run into this crash, this PR would probably still be a good improvement since it prevents unnecessary re-renders...

DevBundle setup to recreate:
```
{
	"name": "imageviewertest",
	"build_dir": "imageviewertest",
	"hdps_repos": [
		{
			"repo": "core",
			"branch": "master"
		},
              {
			"repo": "ImageViewerPlugin",
			"branch": "master"
		}
	]
},
```

Also:
- The `Q_PROPERTY` are confusing to me since any change to `_zoomRectangleTopLeft` and `_zoomRectangleSize` is already follow by a `zoomRectangleChanged` and these properties might only trigger additional calls to that slot. But maybe it does something else, too?

### CODE REVIEW

**Comment by ThomasKroes** [comment]
I am curious to find out what part of https://github.com/ManiVaultStudio/core/commit/b1e70ec64cc05da5a1cd32f49f3145c4091f625c causes this behavior, I will figure out what is the culprit. Regardless, I think it is a good solution!

**Comment by ThomasKroes** [comment]
> The Q_PROPERTY are confusing to me since any change to _zoomRectangleTopLeft and _zoomRectangleSize is already follow by a zoomRectangleChanged and these properties might only trigger additional calls to that slot. But maybe it does something else, too?

These are used for animating the zoom rectangle (if animation is turned on...)

**Review by ThomasKroes — APPROVED** [review]
I think these changes make sense. My only suggestion would be to move the helper functions to the utilities (might be handy for other plugins or the core). Perhaps the `miscellaneous.h` good be a good place?

Just for reference:
- `arePointsEqual(...)`
- `areSizesEqual(...)`
- `areRectsEqual(...)`

**Comment by alxvth** [comment]
- Added the `Q_PROPERTY` again
- Moved the helper functions to the core in `util/Math.h`

Drive-by:
- Updated the cmake and CI (to align with other plugins)

**Comment by ThomasKroes** [comment]
I cannot reproduce this problem, see the video below (master branch 043cb3afc7f99f87481d072912e61e04d012480f).
ImageViewerPluginZooming

**Pull request merged**
